In [58]:
# Preparing Data for PCA
# Next Level Prep | By David H. Nguyen, PhD | Last updated 07/20/25

# NOTE: You will have to write/paste in columns names for Steps 2, 3, 6, and 10!!!

In [12]:
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler

In [13]:
os.chdir(r"C:\Users\Yusif Alabed\Downloads")

# For Windows users, put r in front of "path" because Python interprets "\" differently than Windows. r stands for "raw"
#os.chdir(r"C:\path\to\your\directory")

In [14]:
# Step 1

# Read the CSV file
file_path = 'Metabolic_Negative.csv'
df = pd.read_csv(file_path)
df

# For Windows users, put r in front of "path" 
# df = pd.read_csv(r"C:\path\to\your\file.csv")

,metabolite_identification,3-Methylhistidine,Androsterone sulfate-1,Androsterone sulfate-2,Androsterone sulfate-3,Androsterone sulfate-4,chenodeoxycholic acid,Cholic acid,Creatinine,DCA,...,taurocholic acid,taurodeoxycholate,tauroursodeoxycholate,Tryptophan,Uric acid,ursodeoxycholic acid,Phenyl sulfate,P-cresyl glucuronide,Phenylacetylglycine,Cinnamoylglycine
0,CON-001-S,NaN,2.114174e+04,17812.92479,63956.35128,20586.21694,86227.07040,9964.647757,3267.885101,71566.35110,...,6286.684290,2285.973498,858.178926,115875.71490,171617.36730,767.173717,3.239436e+04,305.128894,336.230500,12541.31441
1,CON-002-S,3334.525297,1.189233e+05,45218.55065,266677.60180,26064.47836,85931.84436,6358.790029,4480.757646,117001.06060,...,10880.221880,52911.064410,8686.191804,226760.65320,144585.97350,23640.764970,2.147592e+05,6318.974611,281.669465,18250.46987
2,CON-003-S,231.901509,1.432525e+05,19925.06791,568728.63130,31634.90607,147275.34340,24901.443620,2302.159970,48170.23351,...,577.063924,558.871184,313.095948,230798.24720,166797.67760,19524.409870,7.204959e+04,846.106350,374.357886,16297.68912
3,CON-004-S,NaN,2.316572e+05,69246.67925,344248.34580,38305.56092,83693.60586,11245.064950,2589.212272,150563.73940,...,1563.335874,8112.527572,290.231950,196700.25460,142807.00300,11421.280690,1.106358e+05,6323.476979,104.064000,15537.20033
4,CON-005-S,NaN,9.560962e+04,31814.00594,184531.32830,19223.66326,52634.11790,7123.723978,2044.275917,68609.23314,...,3716.746528,16908.592950,418.135623,184678.44640,166033.02030,3604.274193,1.656340e+05,945.823196,192.800000,20641.09663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,KD-219-S,45040.145880,4.722602e+04,35449.60737,62247.10201,11806.94468,74743.27260,7755.604803,19443.760010,177697.92630,...,32328.244420,110275.211500,3774.943295,67371.23939,139657.43480,17220.557490,1.163039e+06,54574.686040,986.632500,29564.04830
285,KD-220-S,107.743235,3.204470e+05,98393.58183,464716.29070,82402.79403,40578.73245,9753.687221,51066.596830,19389.98921,...,9053.139234,2792.226039,3017.302116,95162.31868,193711.81240,5377.009645,1.855778e+06,12793.431390,6499.889461,91961.22376
286,KD-221-S,27683.375270,2.002062e+05,27790.63708,981814.89980,75234.21747,18312.63394,3125.053823,45406.877860,18284.69099,...,7065.942034,5361.154114,4400.245454,128066.51270,149694.20430,444.275966,8.900645e+05,26896.416770,4165.105083,102516.99720
287,KD-222-S,6097.221324,1.356452e+06,266284.69850,677629.38130,21027.85825,28453.14544,6704.425517,22118.546540,60714.75158,...,28165.798550,50620.958510,4896.156050,61526.30073,89692.49922,10960.146940,9.626381e+05,141665.044200,822.822500,71759.85228
288,KD-223-S,7075.174467,3.134803e+04,22806.69861,38277.63504,19471.82439,18267.06651,2297.312640,21852.568740,23376.28237,...,2039.583410,7545.054356,4313.255955,62190.10319,175776.92680,14888.937010,5.082773e+05,191850.441800,926.329741,44179.25424

In [15]:
# Extract base name without suffix for naming the output files of this script
base_name = os.path.splitext(os.path.basename(file_path))[0]
base_name

'Metabolic_Negative'

# Collect the desired numerical columns that will be standardized

In [16]:
# Step 2

# Paste in the names of the desired columns
wanted_columns = ['metabolite_identification', '3-Methylhistidine', 'Androsterone sulfate-1', 'Androsterone sulfate-2', 'Androsterone sulfate-3', 'Androsterone sulfate-4', 'chenodeoxycholic acid', 'Cholic acid', 'Creatinine', 'DCA', 'taurocholic acid', 'taurodeoxycholate', 'tauroursodeoxycholate', 'Tryptophan', 'Uric acid', 'ursodeoxycholic acid', 'Phenyl sulfate', 'P-cresyl glucuronide', 'Phenylacetylglycine', 'Cinnamoylglycine']  # replace names with your desired columns
df = df[wanted_columns]
df

,metabolite_identification,3-Methylhistidine,Androsterone sulfate-1,Androsterone sulfate-2,Androsterone sulfate-3,Androsterone sulfate-4,chenodeoxycholic acid,Cholic acid,Creatinine,DCA,taurocholic acid,taurodeoxycholate,tauroursodeoxycholate,Tryptophan,Uric acid,ursodeoxycholic acid,Phenyl sulfate,P-cresyl glucuronide,Phenylacetylglycine,Cinnamoylglycine
0,CON-001-S,NaN,2.114174e+04,17812.92479,63956.35128,20586.21694,86227.07040,9964.647757,3267.885101,71566.35110,6286.684290,2285.973498,858.178926,115875.71490,171617.36730,767.173717,3.239436e+04,305.128894,336.230500,12541.31441
1,CON-002-S,3334.525297,1.189233e+05,45218.55065,266677.60180,26064.47836,85931.84436,6358.790029,4480.757646,117001.06060,10880.221880,52911.064410,8686.191804,226760.65320,144585.97350,23640.764970,2.147592e+05,6318.974611,281.669465,18250.46987
2,CON-003-S,231.901509,1.432525e+05,19925.06791,568728.63130,31634.90607,147275.34340,24901.443620,2302.159970,48170.23351,577.063924,558.871184,313.095948,230798.24720,166797.67760,19524.409870,7.204959e+04,846.106350,374.357886,16297.68912
3,CON-004-S,NaN,2.316572e+05,69246.67925,344248.34580,38305.56092,83693.60586,11245.064950,2589.212272,150563.73940,1563.335874,8112.527572,290.231950,196700.25460,142807.00300,11421.280690,1.106358e+05,6323.476979,104.064000,15537.20033
4,CON-005-S,NaN,9.560962e+04,31814.00594,184531.32830,19223.66326,52634.11790,7123.723978,2044.275917,68609.23314,3716.746528,16908.592950,418.135623,184678.44640,166033.02030,3604.274193,1.656340e+05,945.823196,192.800000,20641.09663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,KD-219-S,45040.145880,4.722602e+04,35449.60737,62247.10201,11806.94468,74743.27260,7755.604803,19443.760010,177697.92630,32328.244420,110275.211500,3774.943295,67371.23939,139657.43480,17220.557490,1.163039e+06,54574.686040,986.632500,29564.04830
285,KD-220-S,107.743235,3.204470e+05,98393.58183,464716.29070,82402.79403,40578.73245,9753.687221,51066.596830,19389.98921,9053.139234,2792.226039,3017.302116,95162.31868,193711.81240,5377.009645,1.855778e+06,12793.431390,6499.889461,91961.22376
286,KD-221-S,27683.375270,2.002062e+05,27790.63708,981814.89980,75234.21747,18312.63394,3125.053823,45406.877860,18284.69099,7065.942034,5361.154114,4400.245454,128066.51270,149694.20430,444.275966,8.900645e+05,26896.416770,4165.105083,102516.99720
287,KD-222-S,6097.221324,1.356452e+06,266284.69850,677629.38130,21027.85825,28453.14544,6704.425517,22118.546540,60714.75158,28165.798550,50620.958510,4896.156050,61526.30073,89692.49922,10960.146940,9.626381e+05,141665.044200,822.822500,71759.85228
288,KD-223-S,7075.174467,3.134803e+04,22806.69861,38277.63504,19471.82439,18267.06651,2297.312640,21852.568740,23376.28237,2039.583410,7545.054356,4313.255955,62190.10319,175776.92680,14888.937010,5.082773e+05,191850.441800,926.329741,44179.25424

In [17]:
df.isnull().sum()

metabolite_identification     0
3-Methylhistidine            45
Androsterone sulfate-1        0
Androsterone sulfate-2        0
Androsterone sulfate-3        0
Androsterone sulfate-4        0
chenodeoxycholic acid         4
Cholic acid                   0
Creatinine                    0
DCA                           0
taurocholic acid              0
taurodeoxycholate             0
tauroursodeoxycholate         0
Tryptophan                    0
Uric acid                     0
ursodeoxycholic acid          5
Phenyl sulfate                0
P-cresyl glucuronide          0
Phenylacetylglycine           0
Cinnamoylglycine              0
dtype: int64

In [18]:
# Delete Any Row that Have Even One Missing Value: 
df = df.dropna()

In [19]:
# Confirm there are no more missing values
df.isnull().sum()

metabolite_identification    0
3-Methylhistidine            0
Androsterone sulfate-1       0
Androsterone sulfate-2       0
Androsterone sulfate-3       0
Androsterone sulfate-4       0
chenodeoxycholic acid        0
Cholic acid                  0
Creatinine                   0
DCA                          0
taurocholic acid             0
taurodeoxycholate            0
tauroursodeoxycholate        0
Tryptophan                   0
Uric acid                    0
ursodeoxycholic acid         0
Phenyl sulfate               0
P-cresyl glucuronide         0
Phenylacetylglycine          0
Cinnamoylglycine             0
dtype: int64

# Collect the columns that contain sample labels and sample names

In [28]:
# Step 3 

# Write or paste in the column names for the sample labels and sample IDs
label_columns = []
labels_df = df[label_columns]
labels_df.head()

Empty DataFrame
Columns: []
Index: [1, 2, 5, 6, 7]

# Isolate numerical columns for PCA

In [29]:
# Step 4

# Get the names of only the numerical columns
numerical_cols = df.select_dtypes(include=['number']).columns
numerical_cols

# Create a subset of containing only numerical columns to remove any label columns
df = df[numerical_cols]
df

,3-Methylhistidine,Androsterone sulfate-1,Androsterone sulfate-2,Androsterone sulfate-3,Androsterone sulfate-4,chenodeoxycholic acid,Cholic acid,Creatinine,DCA,taurocholic acid,taurodeoxycholate,tauroursodeoxycholate,Tryptophan,Uric acid,ursodeoxycholic acid,Phenyl sulfate,P-cresyl glucuronide,Phenylacetylglycine,Cinnamoylglycine
1,3334.525297,1.189233e+05,45218.55065,266677.60180,26064.47836,85931.84436,6358.790029,4480.757646,117001.06060,10880.221880,52911.064410,8686.191804,226760.65320,144585.97350,23640.764970,2.147592e+05,6318.974611,281.669465,18250.46987
2,231.901509,1.432525e+05,19925.06791,568728.63130,31634.90607,147275.34340,24901.443620,2302.159970,48170.23351,577.063924,558.871184,313.095948,230798.24720,166797.67760,19524.409870,7.204959e+04,846.106350,374.357886,16297.68912
5,1375.321006,1.593263e+05,66485.59906,459721.50720,41335.41253,152025.28810,117055.820500,3808.001612,75718.75054,16029.191810,25104.240640,1952.006458,259707.92640,179707.14080,11466.642580,9.458449e+04,656.800000,251.086543,16343.92190
6,137.056927,1.284344e+05,25256.24983,283875.32620,48493.51865,108956.89090,51713.002810,2189.847430,128253.86400,13941.260350,43050.476380,3988.938965,204820.13240,113797.14440,14487.132930,8.222069e+04,412.484965,37.582000,13114.95795
7,61.522274,2.885594e+05,86152.57259,603538.54050,106329.72590,676015.90370,237861.507900,4644.449711,129534.28490,1648.459586,4325.425265,2406.448839,271449.93020,253385.56010,85649.542430,1.099522e+05,3452.312120,176.068000,23846.23018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,45040.145880,4.722602e+04,35449.60737,62247.10201,11806.94468,74743.27260,7755.604803,19443.760010,177697.92630,32328.244420,110275.211500,3774.943295,67371.23939,139657.43480,17220.557490,1.163039e+06,54574.686040,986.632500,29564.04830
285,107.743235,3.204470e+05,98393.58183,464716.29070,82402.79403,40578.73245,9753.687221,51066.596830,19389.98921,9053.139234,2792.226039,3017.302116,95162.31868,193711.81240,5377.009645,1.855778e+06,12793.431390,6499.889461,91961.22376
286,27683.375270,2.002062e+05,27790.63708,981814.89980,75234.21747,18312.63394,3125.053823,45406.877860,18284.69099,7065.942034,5361.154114,4400.245454,128066.51270,149694.20430,444.275966,8.900645e+05,26896.416770,4165.105083,102516.99720
287,6097.221324,1.356452e+06,266284.69850,677629.38130,21027.85825,28453.14544,6704.425517,22118.546540,60714.75158,28165.798550,50620.958510,4896.156050,61526.30073,89692.49922,10960.146940,9.626381e+05,141665.044200,822.822500,71759.85228
288,7075.174467,3.134803e+04,22806.69861,38277.63504,19471.82439,18267.06651,2297.312640,21852.568740,23376.28237,2039.583410,7545.054356,4313.255955,62190.10319,175776.92680,14888.937010,5.082773e+05,191850.441800,926.329741,44179.25424

In [30]:
df.drop(['metabolite_identification'], axis=1, inplace=True)
df

KeyError: "['metabolite_identification'] not found in axis"

# Find outliers in ALL columns that are numerical (Using the IQR Rule of 1.5)

In [26]:
# Step 5

# Define the function
def find_outliers(df):
    outliers = {} 
    all_outlier_indices = set()

    for col in df.select_dtypes(include='number').columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1 
        lower_bound = Q1 - 1.5 * IQR 
        upper_bound = Q3 + 1.5 * IQR 

        # Get indices of outliers for this column
        outlier_indices = df[(df[col] < lower_bound) | (df[col] > upper_bound)].index.tolist()
        outliers[col] = outlier_indices

        # Add to the full set of outlier indices
        all_outlier_indices.update(outlier_indices)

    # Create DataFrame of rows that contain any outlier
    outlier_rows = df.loc[sorted(all_outlier_indices)]

    return outliers, outlier_rows

# Call the function
location, actual_rows = find_outliers(df)
location

{'3-Methylhistidine': [70, 274, 284],
 'Androsterone sulfate-1': [74,
  149,
  157,
  166,
  171,
  173,
  193,
  196,
  198,
  204,
  213,
  268,
  273,
  287],
 'Androsterone sulfate-2': [130, 149, 171, 187, 203, 253, 260],
 'Androsterone sulfate-3': [78, 82, 149, 173, 203, 213, 235, 268, 273, 280],
 'Androsterone sulfate-4': [64, 235, 260],
 'chenodeoxycholic acid': [7,
  15,
  19,
  33,
  41,
  43,
  46,
  47,
  49,
  56,
  58,
  65,
  66,
  79,
  86,
  90,
  119,
  214,
  216,
  253],
 'Cholic acid': [5,
  6,
  7,
  13,
  15,
  19,
  38,
  41,
  43,
  46,
  47,
  49,
  52,
  58,
  65,
  66,
  79,
  86,
  90,
  106,
  119,
  148,
  159,
  182,
  216,
  226,
  253,
  268],
 'Creatinine': [83],
 'DCA': [15, 19, 21, 22, 41, 43, 46, 47, 48, 49, 65, 119, 129, 141],
 'taurocholic acid': [58,
  82,
  86,
  90,
  120,
  123,
  124,
  139,
  142,
  148,
  149,
  152,
  163,
  175,
  176,
  183,
  190,
  213,
  223,
  235,
  237,
  239,
  250,
  251,
  269,
  270,
  273,
  282],
 'taurodeoxycholate': [90,
  96,
  97,
  112,
  124,
  142,
  152,
  162,
  168,
  175,
  176,
  213,
  227,
  236,
  237,
  239,
  250,
  251,
  269,
  270,
  273,
  280,
  281,
  284],
 'tauroursodeoxycholate': [58,
  78,
  79,
  82,
  83,
  86,
  87,
  89,
  90,
  96,
  110,
  124,
  132,
  138,
  139,
  140,
  142,
  144,
  146,
  149,
  156,
  163,
  164,
  167,
  170,
  175,
  181,
  183,
  229,
  256,
  264,
  282],
 'Tryptophan': [],
 'Uric acid': [35, 83],
 'ursodeoxycholic acid': [7,
  19,
  21,
  35,
  43,
  46,
  49,
  56,
  58,
  65,
  66,
  79,
  90,
  119,
  132,
  138,
  141,
  149,
  167,
  191,
  214,
  215,
  229,
  256,
  264],
 'Phenyl sulfate': [119, 154, 167, 180, 237],
 'P-cresyl glucuronide': [70,
  90,
  119,
  120,
  122,
  131,
  135,
  141,
  142,
  143,
  150,
  162,
  189,
  196,
  203,
  208,
  222,
  223,
  263,
  268,
  279,
  281],
 'Phenylacetylglycine': [72,
  78,
  109,
  122,
  123,
  128,
  138,
  146,
  155,
  156,
  204,
  207,
  225,
  228,
  240,
  249,
  269],
 'Cinnamoylglycine': [123, 130, 240]}

# Write/Paste in names of columns that HAVE OUTLIERS

In [27]:
# Step 6

# Paste in column names that have outliers (these need RobustScaler)
hasOutliers = [ '3-Methylhistidine', 'Androsterone sulfate-2', 'Androsterone sulfate-3', 'Androsterone sulfate-4', 'chenodeoxycholic acid', 'Cholic acid', 'Creatinine', ]
hasOutliers

['BMI', 'eGFR']

In [90]:
# Extract which columns do not contain outliers (these need StandardScaler)
column_names = df.columns # Get all column names
noOutliers = [col for col in column_names if col not in hasOutliers]
noOutliers

['Age', 'Urea', 'Creatinine']

# Standardize "noOutliers" via StandardScaler

In [91]:
# Step 7

df = df.copy()  # Ensures df is a standalone DataFrame, not a slice

# Instantiate scaler
meanSD_scaler = StandardScaler()

# Convert numerical columns to float64 (in place)
df[noOutliers] = df[noOutliers].astype('float64')

# Apply scaling
df[noOutliers] = meanSD_scaler.fit_transform(df[noOutliers])

df

          Age        BMI        eGFR      Urea  Creatinine
0    0.861535  19.570000   95.937269 -1.500661   -1.564864
1    0.775425  20.820000   66.667323 -1.510625   -1.506008
2    0.689315  23.830000   96.027921 -1.570405   -1.559555
4   -0.602333  21.190000  110.468885 -1.580369   -1.573173
5    0.344876  23.920000   95.105345 -1.560442   -1.550092
..        ...        ...         ...       ...         ...
820  0.172656  23.040020    3.511940  0.717198    1.150375
821  0.086546  18.832392    6.133173  1.020086    0.109426
822  0.344876  19.270578    8.875903 -0.994519   -0.661477
823  1.292085  17.301038    5.713564 -0.276156   -0.299106
824 -1.549542  22.768834    5.467900  0.188140    0.058648

[790 rows x 5 columns]

# Standardize "hasOutliers" via RobustScaler

In [92]:
# Step 8

df = df.copy()  # Ensures df is a standalone DataFrame, not a slice

# Instantiate scaler
medIQR_scaler = RobustScaler()

# Convert numerical columns to float64 (in place)
df[hasOutliers] = df[hasOutliers].astype('float64')

# Apply scaling
df[hasOutliers] = medIQR_scaler.fit_transform(df[hasOutliers])

df

          Age       BMI       eGFR      Urea  Creatinine
0    0.861535 -0.727188  13.282973 -1.500661   -1.564864
1    0.775425 -0.493516   9.004417 -1.510625   -1.506008
2    0.689315  0.069167  13.296224 -1.570405   -1.559555
4   -0.602333 -0.424349  15.407143 -1.580369   -1.573173
5    0.344876  0.085991  13.161366 -1.560442   -1.550092
..        ...       ...        ...       ...         ...
820  0.172656 -0.078510  -0.227367  0.717198    1.150375
821  0.086546 -0.865075   0.155794  1.020086    0.109426
822  0.344876 -0.783161   0.556714 -0.994519   -0.661477
823  1.292085 -1.151342   0.094457 -0.276156   -0.299106
824 -1.549542 -0.129205   0.058547  0.188140    0.058648

[790 rows x 5 columns]

In [93]:
# Step 9

# Combine the label columns with the standardized numerical columns
combined_df = pd.concat([labels_df, df], axis=1)

In [94]:
# Step 10

# Create new output filename
fileName = base_name + "_standardized4PCA.csv"

# Save the DataFrame
combined_df.to_csv(fileName, index=False)